// examples/docs/getting-started/nuxtjs/finished/pages/[topic].vue
<script lang="ts" setup>
import Layout from "../src/components/Layout.vue";
import content from "../lib/content.json";

const route = useRoute();
const topic = content.find((entry) => entry.id == route.params.topic);
</script>

<template>
  <Layout :content="content" :fields="topic.fields" />
</template>

// examples/docs/getting-started/nextjs/no-uniform/pages/[topic].jsx
import Layout from "../src/components/Layout";

import content from "../content/content.json";

//
//Next.js uses this function to determine the
//dynamic routes this component can handle.
//It should handle all routes that represent
//topics.
export async function getStaticPaths() {
  const topics = content.filter((e) => e.type == "topic");
  const paths = topics.map((e) => {
    return { params: { topic: e.id } };
  });
  return { paths, fallback: false };
}

//
//Since this component supports dynamic routes,
//Next.js uses this function to determine the
//props to use based on the current route.
//This function returns the "fields" values
//from the content file.
export async function getStaticProps({ params }) {
  const topic = content.find((e) => e.id == params.topic);
  return { props: { fields: topic?.fields } };
}

export default function Topic({ fields }) {
  return <Layout content={content} fields={fields} />;
}
