// examples/docs/intro-to-context/nextjs/finished/src/components/HomeLayout.jsx
import Head from "next/head";

import Body from "./Body";
import Footer from "./Footer";

import { Personalize } from '@uniformdev/context-react';
import variants from "../../content/home-variants.json";

export default function HomeLayout({ fields }) {
  const { title } = fields;
  return (
    <div className="container">
      <Head>
        <title>{title}</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Personalize
        variations={variants} 
        name="bodyPersonalized" 
        component={Body} 
      />
      <Footer />
    </div>
  );
}

// examples/docs/intro-to-context/nuxtjs/finished/components/HomeLayout.vue
<script lang="ts" setup>
import { type PersonalizedVariant } from "@uniformdev/context";
import { Personalize } from "@uniformdev/context-vue";
import Body from "./Body.vue";
import Footer from "./Footer.vue";
import variantsJson from "../content/home-variants.json";

defineProps<{ fields: { title: string; description: string } }>();
const variants = variantsJson as PersonalizedVariant[];
</script>

<template>
  <div class="container">
    <Head>
      <Title>{{ fields.title }}</Title>
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Personalize
      :variations="variants"
      name="bodyPersonalized"
      :component="(Body as any)"
    />
    <Footer />
  </div>
</template>
