// examples/nuxt3-starter-netlify-edge/components/Navigation.vue
<script lang="ts" setup>
export interface NavLink {
  title: string;
  url: string;
}
export interface Props {
  navLinks: Array<NavLink>;
}

const props = defineProps<Props>();

const isNoteVisible = props.navLinks.length <= 1;
</script>

<template>
  <div class="navigation">
    <span v-for="({ url, title }, i) in navLinks">
      <NuxtLink :key="url" :href="url">{{ title }}</NuxtLink>
    </span>
    <span v-if="isNoteVisible" class="note">
      (create a new composition to see a link to it here...)
    </span>
  </div>
</template>

<style scoped>
.navigation {
  padding: 2rem 0;
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
}

.navigation span {
  padding-left: 2rem;
}

.note {
  font-size: 1rem;
  font-style: italic;
}
</style>

// examples/nextjs-starter/components/Navigation.tsx
import Link from "next/link";

export interface NavigationProps {
  navLinks: Array<NavLink>;
}

export interface NavLink {
  title: string;
  url: string;
}

const Navigation: React.FC<NavigationProps> = ({
  navLinks,
}: NavigationProps) => {
  if (!navLinks) {
    return null;
  }

  const links = [...navLinks.filter((l) => l.url !== "/")];
  links.unshift({ url: "/", title: "Home" });
  return (
    <div className="navigation">
      {links.map((e: NavLink, i: number) => (
        <span key={i}>
          <Link href={e.url}>{e.title}</Link>
        </span>
      ))}
      {links.length <= 1 ? (
        <span className="note">
          (create a new composition to see a link to it here...)
        </span>
      ) : null}
    </div>
  );
};

export default Navigation;
