// examples/sveltekit-starter/src/lib/components/Hero.svelte
<script lang="ts">
  import { UniformText, UniformRichText } from "@uniformdev/canvas-svelte";
</script>

<section class="hero">
  <UniformText parameterId="title" as="h1" placeholder="Enter hero title" />
  <div class="subtitle">
    <UniformRichText parameterId="description" as="div"placeholder="Enter hero description" />
  </div>
</section>

<style>
  .hero {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 4rem 2rem;
    border-radius: 12px;
    margin-bottom: 2rem;
    text-align: center;
  }

  h1 {
    margin: 0 0 1rem 0;
    font-size: 2.5rem;
    font-weight: 700;
  }

  .subtitle {
    margin: 0 0 1.5rem 0;
    opacity: 0.9;
    font-size: 1.25rem;
  }
</style>

// examples/nuxtjs-starter/components/Hero.vue
<script lang="ts" setup>
import type { ComponentInstance } from "@uniformdev/canvas";
import type { UniformRichTextNodeProps } from "@uniformdev/canvas-vue";

interface Props {
  title: string;
  description?: UniformRichTextNodeProps["node"];
  component: ComponentInstance;
}

defineProps<Props>();
</script>
<template>
  <div>
    <UniformText
      parameterId="title"
      as="h1"
      class="title"
      placeholder="Insert a title"
    />
    <UniformRichText
      parameter-id="description"
      as="div"
      class="description"
      placeholder="Insert a description"
    />
  </div>
</template>

<style scoped>
.title a {
  color: #0070f3;
  text-decoration: none;
}

.title a:hover,
.title a:focus,
.title a:active {
  text-decoration: underline;
}

.title {
  color: #438fd5;
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
}

.title,
.description {
  text-align: center;
}

.description {
  margin: 1rem 0;
  line-height: 1.5;
  font-size: 1.5rem;
}
</style>
