// examples/segment-netlify-edge-personalization/components/PageComposition.tsx
import React from "react";
import Head from "next/head";
import { RootComponentInstance } from "@uniformdev/canvas";
import {
  UniformComposition,
  UniformSlot,
  createUniformApiEnhancer,
} from "@uniformdev/canvas-react";
import Navigation, { NavLink } from "./Navigation";
import Footer from "./Footer";
import "../lib/uniform/components";

export default function PageComposition({
  composition,
  navLinks,
}: {
  preview: boolean;
  composition: RootComponentInstance;
  navLinks: Array<NavLink>;
}) {
  const contextualEditingEnhancer = createUniformApiEnhancer({
    apiUrl: "/api/preview",
  });
  const { metaTitle } = composition?.parameters || {};
  const title = metaTitle?.value as string;
  if (!composition) {
    return null;
  }
  return (
    <>
      <Head>
        <title>{title}</title>
      </Head>
      <Navigation navLinks={navLinks} />
      {!composition ? null : (
        <UniformComposition
          data={composition}
          contextualEditingEnhancer={contextualEditingEnhancer}
        >
          <UniformSlot name="content" />
        </UniformComposition>
      )}
      <Footer />
    </>
  );
}

// examples/nuxtjs-starter/components/PageComposition.vue
<script lang="ts" setup>
import type {
  ComponentInstance,
  RootComponentInstance,
} from "@uniformdev/canvas";
import { DefaultNotImplementedComponent } from "@uniformdev/canvas-vue";
import Hero from "./Hero.vue";

import type { Props as NavigationProps } from "./Navigation.vue";

// register your new components here
const componentResolver = (component: ComponentInstance) => {
  if (component.type == "hero") {
    return Hero;
  }
  return DefaultNotImplementedComponent;
};

interface Props {
  composition: RootComponentInstance;
  navLinks: NavigationProps["navLinks"];
}

const props = defineProps<Props>();

const { composition } = props;
const { metaTitle } = composition?.parameters || {};
const title = metaTitle?.value as string;
</script>

<template>
  <div class="page">
    <Head>
      <Title>{{ title }}</Title>
    </Head>
    <Navigation :navLinks="navLinks" />
    <UniformComposition
      :data="composition"
      :resolveRenderer="componentResolver"
    >
      <UniformSlot name="content" />
    </UniformComposition>
    <Footer />
  </div>
</template>

<style scoped>
.page {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}
</style>
