// examples/docs/getting-started/nuxtjs/finished/components/Layout.vue
<script lang="ts" setup>
import type { Content, Fields } from "../types";
import Body from "./Body.vue";
import Footer from "./Footer.vue";

defineProps<{
  fields: Fields;
  content: Content;
}>();
</script>

<template>
  <div class="container">
    <Head>
      <Title>{{ fields.title }}</Title>
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Body :fields="fields" :content="content" />
    <Footer />
  </div>
</template>

// examples/docs/intro-to-context/nextjs/no-uniform/src/components/Layout.jsx
import Head from "next/head";

import Body from "./Body";
import Footer from "./Footer";

export default function Layout({ fields, content }) {
  const { title } = fields;
  return (
    <div className="container">
      <Head>
        <title>{title}</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body fields={fields} content={content} />
      <Footer />
    </div>
  );
}
