// examples/docs/getting-started/nuxtjs/finished/components/Navigation.vue
<script lang="ts" setup>
import type { Content } from "../types";

const props = defineProps<{ content: Content }>();
const links = computed(() => props.content.filter((c) => c.url));
</script>
<template>
  <div>
    <span v-for="(link, i) in links">
      {{ i > 0 ? " :: " : null }}
      <NuxtLink :href="link.url">{{ link.fields.title }}</NuxtLink>
    </span>
  </div>
</template>

// examples/docs/intro-to-canvas/nextjs/finished/src/components/Navigation.jsx
import Link from "next/link";

export default function Navigation({ content }) {
  const links = content.filter((c) => c.url);
  return (
    <div>
      {links.map((e, i) => {
        const separator = i > 0 ? " :: " : null;
        return (
          <span key={e.id}>
            {separator}
            <Link href={e.url}>{e.fields.title}</Link>
          </span>
        );
      })}
    </div>
  );
}
