// examples/modulefederation-tanstackrouter/host/src/components/uniform/Page.tsx
import { UniformSlot } from "@uniformdev/canvas-react";
import { SiteHeader } from "../ui/SiteHeader.tsx"
import { SiteFooter } from "../ui/SiteFooter.tsx"

const Page = () => {
  return (
    <div>
      <SiteHeader />
      <div className="p-4">
        <UniformSlot name="content" />
      </div>
      <SiteFooter />
    </div>
  )
};

export default Page;

// examples/sveltekit-demo/src/lib/components/uniform/page.svelte
<script lang="ts">
  import { UniformSlot } from '@uniformdev/canvas-svelte';
  import type { ComponentProps } from '@uniformdev/canvas-svelte';

  interface Props extends ComponentProps<{}> {}

  let {}: Props = $props();
</script>

<!-- Page composition - renders the content slot -->
<UniformSlot name="content" />
