// examples/docs/getting-started/nuxtjs/finished/components/Body.vue
<script lang="ts" setup>
import type { Fields } from "../types";
import content from "../lib/content.json";
import Navigation from "./Navigation.vue";

defineProps<{ fields: Fields }>();
</script>

<template>
  <main class="main">
    <Navigation :content="content" />
    <h1 class="title">{{ fields.title }}</h1>
    <p class="description">{{ fields.description }}</p>
  </main>
</template>

// examples/docs/getting-started/nextjs/finished/src/components/Body.jsx
import Navigation from "./Navigation";

import content from "../../lib/content.json";

export default function Body(props) {
  const { fields } = props;
  const title = fields?.title;
  const description = fields?.description;
  return (
    <main className="main">
      <Navigation content={content} />
      <h1 className="title">{title}</h1>
      <p className="description">{description}</p>
    </main>
  );
}
