// examples/docs/getting-started/nuxtjs/finished/components/LayoutCanvas.vue
<script lang="ts" setup>
import Footer from "./Footer.vue";

defineProps<{ title: string }>();
</script>

<template>
  <div class="container">
    <Head>
      <Title>{{ title }}</Title>
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <SlotContent name="body" />
    <Footer />
  </div>
</template>

// examples/docs/getting-started/nextjs/finished/src/components/LayoutCanvas.jsx
import Head from "next/head";
import { Slot } from "@uniformdev/canvas-react";

import Footer from "./Footer";

export default function LayoutCanvas({ title }) {
  return (
    <div className="container">
      <Head>
        <title>{title}</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slot name="body" />
      <Footer />
    </div>
  );
}
